### ISSUE TITLE
Not working with 2022.1

### ISSUE THREAD

**Issue by KluDev** [overpas/svg-to-compose-intellij#13]
On the marketplace the following error occurs:

Not compatible with the version of your running IDE (IntelliJ IDEA 2022.1)

Maybe it's working anyway. I didn't test it

**Comment by overpas** [comment]
Yes, it's the plugin is mainly targeted at Android Studio, and intellij core version in AS has a lag compared to IDEA. But it may be possible to target the latest IDEA version instead

**Comment by DevSrSouza** [comment]
I also test it on the AS Canary version and did not work as well.

**Comment by russellbanks** [comment]
It would be nice if this targeted the latest IDEA versions as Compose Multiplatform would benefit from this plugin.

**Comment by overpas** [comment]
Should work since 0.7 version
