### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by Bradleycorn** [overpas/svg-to-compose-intellij#5]
I tried to use the plugin on a folder with a single XML Vector Drawable. 
I'm using Android Studio Bumblebee (2021.1.1 Patch 2)

I used the following inputs:

**Accessor Name**: MyIconPack
**Output Directory**: /Android/Projects/MyProject/app/src/main/kotlin/com/myapp/ui/icons
**Vector Images Directory**: /Android/Projects/MyProject/app/src/main/res/drawable
(note: this directory has one file, ic_races.xml)
**Vector Image Type**: DRAWABLE
**All Assets Property Name**: AllIcons

And the output I got was a single file, `__MyIconPack.kt`, with contents:
```
import androidx.compose.ui.graphics.vector.ImageVector
import kotlin.collections.List as ____KtList

public object MyIconPack

private var __AllIcons: ____KtList<ImageVector>? = null

public val MyIconPack.AllIcons: ____KtList<ImageVector>
  get() {
    if (__AllIcons != null) {
      return __AllIcons!!
    }
    __AllIcons= listOf()
    return __AllIcons!!
  }
```

Nothing in the Android Studio event log ... 

Am I doing something wrong?

**Comment by overpas** [comment]
This seems to be a bug, I'll try to do something about it, thanks

**Comment by Bradleycorn** [comment]
Thanks @overpas. It looks like the underlying converter library hasn't been updated in several months. I wonder if it needs some updates to work with recent versions of compose/material?...
